---
title: "K selection"
author: "Elena Peterson"
date: '2024-03-14'
output: html_document
---

This script plots the similarity metrics for each k, from k =  5 to 11.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages
```{r}
library(ggplot2)
```

Load data files
```{r}

# no sampling, 5 repeats, and extra metrics
k_5reps = read.csv("../Data/Brain_Data/k_selection_sim_std2.csv",header=TRUE,stringsAsFactors = FALSE)

# no sampling, but 10 repeats, and extra metrics
k_10reps = read.csv("../Data/Brain_Data/k_selection_sim_std3_r10.csv",header=TRUE,stringsAsFactors = FALSE)

# sampling with 10 repeats
k_subsample = read.csv("../Data/Brain_Data/k_selection_std_sample_r10.csv",header=TRUE,stringsAsFactors = FALSE)

```

Test 1: 5 repeats, no subsampling
```{r}

# k by average similarity
g1 <- ggplot(k_5reps, aes(cluster_k, all_sims_av)) + 
  geom_line(color="blue") + 
  geom_point(color="blue") + 
  #xlab("Cylinders") + # x-axis label
  ylab("Mean Similarity") + # y-axis-label
  #ggtitle("Horsepower by Cylinders") + # Title of plot
  scale_x_continuous(name="K Clusters",breaks=seq(5,11))+
  theme_classic(base_size=12) + 
  theme(plot.title=element_text(hjust = .5),aspect.ratio = 1) 
g1

# k by similarity sd
g2 <- ggplot(k_5reps, aes(cluster_k, all_sims_sd)) + 
  geom_line(color="red") + 
  geom_point(color="red") + 
  #xlab("Cylinders") + # x-axis label
  #ylab("Horsepower") + # y-axis-label
  #ggtitle("Horsepower by Cylinders") + # Title of plot
  theme_classic(base_size=18) + 
  theme(plot.title=element_text(hjust = .5),aspect.ratio = 1) 
g2

```
Test 2: 10 repeats, no subsampling
```{r}

g3 <- ggplot(k_10reps, aes(cluster_k, all_sims_av)) + 
  geom_line(color="blue") + 
  geom_point(color="blue") + 
  #xlab("Cylinders") + # x-axis label
  ylab("Mean Similarity") + # y-axis-label
  #ggtitle("Horsepower by Cylinders") + # Title of plot
  scale_x_continuous(name="K Clusters",breaks=seq(5,11))+
  #scale_y_continuous(name="Mean Similarity",breaks=seq(0,40,5))+
  theme_classic(base_size=18) + 
  theme(plot.title=element_text(hjust = .5),aspect.ratio = 1) 
g3

g4 <- ggplot(k_10reps, aes(cluster_k, all_sims_sd)) + 
  geom_line(color="red") + 
  geom_point(color="red") + 
  #xlab("Cylinders") + # x-axis label
  #ylab("Horsepower") + # y-axis-label
  #ggtitle("Horsepower by Cylinders") + # Title of plot
  theme_classic(base_size=18) + 
  theme(plot.title=element_text(hjust = .5),aspect.ratio = 1) 
g4

```
Test 3: 10 repeats, with subsampling

```{r}
g5 <- ggplot(k_subsample, aes(cluster_k, all_sims_av)) + 
  geom_line(color="blue") + 
  geom_point(color="blue") + 
  #xlab("Cylinders") + # x-axis label
  #ylab("Horsepower") + # y-axis-label
  #ggtitle("Horsepower by Cylinders") + # Title of plot
  theme_classic(base_size=18) + 
  theme(plot.title=element_text(hjust = .5),aspect.ratio = 1) 
g5

g6 <- ggplot(k_subsample, aes(cluster_k, all_sims_sd)) + 
  geom_line(color="red") + 
  geom_point(color="red") + 
  #xlab("Cylinders") + # x-axis label
  #ylab("Horsepower") + # y-axis-label
  #ggtitle("Horsepower by Cylinders") + # Title of plot
  theme_classic(base_size=18) + 
  theme(plot.title=element_text(hjust = .5),aspect.ratio = 1) 
g6

```


Other metrics
```{r}
g3 <- ggplot(d2, aes(cluster_k, cal)) + 
  geom_line(color="purple") + 
  geom_point(color="purple") + 
  #xlab("Cylinders") + # x-axis label
  #ylab("Horsepower") + # y-axis-label
  #ggtitle("Horsepower by Cylinders") + # Title of plot
  theme_classic(base_size=18) + 
  theme(plot.title=element_text(hjust = .5),aspect.ratio = 1) 
g3

g4 <- ggplot(d2, aes(cluster_k, dave)) + 
  geom_line(color="green") + 
  geom_point(color="green") + 
  #xlab("Cylinders") + # x-axis label
  #ylab("Horsepower") + # y-axis-label
  #ggtitle("Horsepower by Cylinders") + # Title of plot
  theme_classic(base_size=18) + 
  theme(plot.title=element_text(hjust = .5),aspect.ratio = 1) 
g4

g5 <- ggplot(d2, aes(cluster_k, sil)) + 
  geom_line(color="orange") + 
  geom_point(color="orange") + 
  #xlab("Cylinders") + # x-axis label
  #ylab("Horsepower") + # y-axis-label
  #ggtitle("Horsepower by Cylinders") + # Title of plot
  theme_classic(base_size=18) + 
  theme(plot.title=element_text(hjust = .5),aspect.ratio = 1) 
g5


```

