---
title: "CAP validation analyses"
author: "Elena Peterson"
date: "2024-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages & data files
```{r}
library(lme4)
library(lmerTest)

dwide = read.csv("../Data/Brain_Data/CAP_measures_overall_2024-04-10.csv",stringsAsFactors = FALSE, header=TRUE)
dlong = read.csv("../Data/Brain_Data/CAP_k8_long_sequence_2024-03-29.csv",stringsAsFactors = FALSE, header=TRUE)

```
Identify states that are responsive to changes in WM load
```{r}
t.test(dwide$ts_1_0back, dwide$ts_1_2back, paired=TRUE) # sig., 0-back responsive
t.test(dwide$ts_2_0back, dwide$ts_2_2back, paired=TRUE) # sig., 0-back responsive
t.test(dwide$ts_3_0back, dwide$ts_3_2back, paired=TRUE) # marginal, 0-back responsive
t.test(dwide$ts_4_0back, dwide$ts_4_2back, paired=TRUE) # ns
t.test(dwide$ts_5_0back, dwide$ts_5_2back, paired=TRUE) # ns
t.test(dwide$ts_6_0back, dwide$ts_6_2back, paired=TRUE) # sig. # this one, 2-back responsive
t.test(dwide$ts_7_0back, dwide$ts_7_2back, paired=TRUE) # sig. 0-back responsive
t.test(dwide$ts_8_0back, dwide$ts_8_2back, paired=TRUE) # sig., 2-back responsive

```
Check how task events relate to state transitions
```{r}
mod1 <- lmer(errors2 ~ state_transit + (state_transit |subid), data=dlong, na.action=na.omit); summary(mod1) 
# marginal, p=.06

# try again, but not counting missed responses
mod1a <- lmer(errors_resp2 ~ state_transit + (state_transit |subid), data=dlong, na.action=na.omit); summary(mod1a) 
# less sig.

mod2 <- lmer(long_rts2 ~ state_transit + (state_transit |subid), data=dlong, na.action=na.omit,control = lmerControl(calc.derivs = FALSE)); summary(mod2) 
# not sig.

# this one is significant... but convergence error
mod3 <- lmer(transit_dist ~ state_transit + (state_transit|subid), data=dlong, na.action=na.omit,control = lmerControl(calc.derivs = FALSE)); summary(mod3)
# p<.001

# significant:
mod3_fixed = lm(transit_dist ~ state_transit, data=dlong2)
summary(mod3_fixed)

```

