---
title: "Posthoc Tests"
author: "Elena Peterson"
date: "2024-03-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read in files

Consider MFI...
```{r}
library(corrplot)
library(Hmisc)
source("~/Desktop/Stats_TA_Fall23/gradstats_funcs.R")

dtest <- read.csv("../Data/Merged_Data/Merged_Data_9s_2024-04-09_cleaned.csv",header=TRUE,stringsAsFactors = FALSE)
dim(dtest)


#dtest2 <- read.csv("../Data/Merged_Data/...",header=TRUE,stringsAsFactors = FALSE)
#dim(dtest2)

dlong <- read.csv("../Data/Merged_Data/Merged_Data_9s_2024-04-16.csv",header=TRUE,stringsAsFactors = FALSE)
names(dlong)

dwide = read.csv("../Data/Merged_Data/Merged_Data_Wide_2024-04-17.csv",stringsAsFactors = FALSE, header = TRUE)
names(dwide)

bdi_mean = aggregate(dlong$bdi2_total, by=list(dlong$participant), mean, na.rm=T)
names(bdi_mean) = c("participant", "bdi_raw_mean")
bdi_mean$bdi_raw_var = aggregate(dlong$bdi2_total, by=list(dlong$participant), var, na.rm=T)$x

#dwide2 = merge(dwide, bdi_mean, all.x = T)

bdi1 = dlong[dlong$session==1,]
bdi1 = subset(bdi1, select = c("participant", "bdi2_total"))
names(bdi1) = c("participant", "baseline_bdi")

dwide2 = merge(dwide, bdi1, all.x = T)
dwide2 = merge(dwide2, bdi_mean, all.x = T)
dwide2 = dwide2[!is.na(dwide2$logv_mean),]
rownames(dwide2) = NULL
names(dwide2)

```

```{r}
dwide_out = dwide2[-c(69, 86, 120),]

hist(dwide2$baseline_bdi)
# checking results with simple models
summary(lm(overall_ts_1 ~ bdi_raw_mean, data=dwide_out))
summary(lm(overall_ts_6 ~ bdi_raw_mean, data=dwide_out))
summary(lm(overall_ps_6 ~ bdi_raw_mean, data=dwide_out))

summary(lm(overall_ts_1 ~ bdi_raw_var, data=dwide_out))
summary(lm(overall_ts_6 ~ bdi_raw_var, data=dwide_out))
summary(lm(overall_ps_6 ~ bdi_raw_var, data=dwide_out))

```

```{r}
# define function
sumdiff = function(somelist) {
  sum(diff(sort(somelist)))
}

```

```{r}
all_ts = dwide2[,grep("_ts_",names(dwide2),value=TRUE)]

dwide2$ts_sumdiff = apply(all_ts, 1, sumdiff)
dwide2$ts_var = apply(all_ts, 1, var)

cor.test(dwide2$ts_var, dwide2$ts_sumdiff) # sig, similar measure

summary(lm(ts_sumdiff ~ logv_mean, data=dwide2)) # not sig, trending though
summary(lm(ts_var ~ logv_mean, data=dwide2)) # ns

summary(lm(ts_6_2back ~ age, data=dwide2)) # interesting

dwide2$ts_6_2b_z = (dwide2$ts_6_2back - mean(dwide2$ts_6_2back))/sd(dwide2$ts_6_2back)
dwide2$age_z = (dwide2$age - mean(dwide2$age))/sd(dwide2$age)
summary(lm(ts_6_2back ~ age, data=dwide2)) # interesting
summary(lm(ts_6_2b_z ~ age_z, data=dwide2))
```
Make correlation matrix for brain measures
```{r}
cap = subset(dx, select = c("overall_ps_1", "overall_ps_2", "overall_ps_3", "overall_ps_4", "overall_ps_5", "overall_ps_6", "overall_ps_7", "overall_ps_8", "overall_ts_1", "overall_ts_2", "overall_ts_3", "overall_ts_4", "overall_ts_5", "overall_ts_6", "overall_ts_7", "overall_ts_8" ))

ts = subset(dx, select = c("overall_ts_1", "overall_ts_2", "overall_ts_3", "overall_ts_4", "overall_ts_5", "overall_ts_6", "overall_ts_7", "overall_ts_8" ))

ts0 = subset(dwide, select = c(ts_1_0back, ts_2_0back, ts_3_0back, ts_4_0back, 
                               ts_5_0back, ts_6_0back, ts_7_0back, ts_8_0back))

ts2 = subset(dwide, select = c(ts_1_2back, ts_2_2back, ts_3_2back, ts_4_2back, 
                               ts_5_2back, ts_6_2back, ts_7_2back, ts_8_2back))


# all brain measures
Mcap = cor(cap, use="pairwise.complete.obs")

# plot cor matrix
pal1 = rev(COL2('RdBu', 200))
corrplot(Mcap, method = 'square', type = 'lower', diag = FALSE, col=pal1) # order fx are intersting

# TS only
M_ts = cor(ts, use="pairwise.complete.obs")

# plot cor matrix
 # order fx are intersting
corrplot(M_ts, method = 'square', type = 'lower', diag = FALSE, col=pal1, order = 'FPC')

# TS by condition
M_ts0 = cor(ts0, use="pairwise.complete.obs")
M_ts2 = cor(ts2, use="pairwise.complete.obs")

# plot cor matrix
 # order fx are intersting
corrplot(M_ts0, method = 'square', type = 'lower', diag = FALSE, col=pal1, order = 'FPC')
corrplot(M_ts2, method = 'square', type = 'lower', diag = FALSE, col=pal1, order = 'FPC')

```

Outlier checks
```{r}
dwide2 = dwide2[!is.na(dwide2$logv_mean),]
rownames(dwide2) = NULL

mod1 = lm(logv_mean ~ OverallAcc, data=dwide2)
summary(mod1)
plot(dwide2$logv_mean ~ dwide2$OverallAcc)
#sort(cooks.distance(mod1), decreasing = TRUE)
plot(mod1, which=4) #67, 69, 120

mod2 = lm(dwide2$logv_mean ~ dwide2$overall_ts_6)
summary(mod2)
plot(dwide2$logv_mean ~ dwide2$overall_ts_6)
plot(mod2, which=4) #69, 86, 120

mod3 = lm(dwide2$logv_mean ~ dwide2$overall_ts_1)
summary(mod3)
plot(dwide2$logv_mean ~ dwide2$overall_ts_1)
plot(mod3, which=4) #69, 86, 111

mod4 = lm(dwide2$logv_mean ~ dwide2$overall_ps_6)
summary(mod4)
plot(dwide2$logv_mean ~ dwide2$overall_ps_6)
plot(mod4, which=4) #69, 86, 120

#69, 86, 120 come up repeatedly
dwide_out = dwide2[-c(69, 86, 120),]

sum(dwide$logv_mean < 0, na.rm=T) #11 ppl have negative variances
sum(dwide2$bdi_raw_mean == 0, na.rm=T) #9 people with zeros
mod1a = lm(dwide_out$logv_mean ~ dwide_out$OverallAcc); summary(mod1a) # still sig.
mod2a = lm(dwide_out$logv_mean ~ dwide_out$overall_ts_6); summary(mod2a) #ns
mod3a = lm(dwide_out$logv_mean ~ dwide_out$overall_ts_1); summary(mod3a) #ns
mod4a = lm(dwide_out$logv_mean ~ dwide_out$overall_ps_6); summary(mod4a) #ns

plot(dwide_out$logv_mean ~ dwide_out$overall_ps_6)
plot(dwide_out$logv_mean ~ dwide_out$overall_ts_6)
plot(dwide_out$logv_mean ~ dwide_out$overall_ts_1)
```



FDR correction
```{r}
# fill in list of p-values below- whatever is involved in mediation

# first, direct path c'- does EF predict depression trajectories? (3 paths)
# next, a paths - does EF predict brain measures? (1 brain state x 3 measures x 1 predictor = 3)
# next, b paths - do brain measures predict depression trajectories? (1 brain state x 3 measures x 3 outcomes = 9)
# total = 15 p-values

# 5/31/24 - age & sex on both outcomes
mplus_ps = c(.445, .211, .409, # total path, not indirect
             .349, .023, .470, # ts6 x 3 bdi
             .355, .005, .303, # ps6 x 3 bdi
             .372, .465, .349, # trx61 x 3 bdi
             .383, .079, .444 ) # EF x 3 brain

mplus_ps2 = mplus_ps*2 #one-tailed p-vals reported in mplus



names(mplus_ps2) = c("EF_Phi", "EF_Var", "EF_Mean", # c paths
                 "TS6_Phi", "TS6_Var", "TS6_Mean", # pseudo-b path (not controlling for x)
                 "PS6_Phi", "PS6_Var", "PS6_Mean", # pseudo-b path (not controlling for x)
                 "TX61_Phi", "TX61_Var", "TX61_Mean", # pseudo-b path (not controlling for x)
                 "EF_TS6", "EF_PS6", "EF_TX61") # a paths

# nothing survived correction...
sort(round(p.adjust(mplus_ps2,"BH"),3))

round(p.adjust(mplus_ps2,"fdr"),3)
mplus_ps2
```


```{r}

# Trying again but running everything in one model (a,b,c, indirect paths):
############################################################################
# what about averaging redundant paths?
# check correlation between ts6, ps6, trx61

mplus_ps = c(.082, .182, .367, #PS6: .046, .214, .379; #TRX61: .046, .173, .407; 
             
             .190, .016, .172, 
             .173, .013, .109,
             .354, .225, .186,
              
             .471, .475, .456, 
             .396, .398, .353,
             .377, .448, .386,
             
             .454, .352, .301)

mplus_ps2 = mplus_ps*2 #one-tailed p-vals reported in mplus

#reg_ps = c(0.875, 0.749, 0.59)

#all_ps = c(mplus_ps2, reg_ps)

names(mplus_ps2) = c("EF_Phi_Prime", "EF_Var_Prime", "EF_Mean_Prime",   # c' paths- just use one?
                 
                  "TS6_Phi", "TS6_Var", "TS6_Mean",   # b paths
                 "PS6_Phi", "PS6_Var", "PS6_Mean",    # b paths
                 "TX61_Phi", "TX61_Var", "TX61_Mean", # b paths
                 
                 "Indir1_TS6", "Indir2_TS6", "Indir3_TS6", # indir paths
                 "Indir1_PS6", "Indir2_PS6", "Indir3_PS6", # indir paths
                 "Indir1_TX61", "Indir2_TX61", "Indir3_TX61", # indir paths
                 
                 "EF_TS6", "EF_PS6", "EF_TX61") # a paths

# nothing survived correction...
sort(round(p.adjust(mplus_ps2,"fdr"),3))

# still doesn't survive correction, worse even

cor.test(d$overall_ps_6, d$overall_ts_6) # highly correlated- r = .71

cor.test(d$overall_ps_6, d$trx_61) # not correlated

cor.test(d$overall_ts_6, d$trx_61) # somewhat correlated (r=.28, p<.001)

# or, correct within each model? Or is that worse?
```
