---
title: "CAP validation analyses"
author: "Elena Peterson"
date: "2024-04-11"
output: html_document
---

Script for comparing movement & SNR of CAP states.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages & data files
```{r}
library(lme4)
library(lmerTest)
library(ggpubr)

blong = read.csv("../../Data/Brain_Data/CAP_k8_long_sequence_2024-03-29.csv",stringsAsFactors = FALSE, header=TRUE)
names(blong); dim(blong)

```


```{r}
setwd("../../Data/Movement_Relative/")

alldata = list.files(recursive = TRUE, pattern = "Movement_RelativeRMS.txt")
head(alldata)
subnames = substr(alldata,1,7)
alldata = lapply(alldata, read.csv, header=FALSE) 

for (sub in 1:length(alldata)) {
  alldata[[sub]]$volnums = 1:720
  alldata[[sub]]$subid = subnames[sub]
}

movementRel = Reduce(function(...)merge(...,all=T),alldata)
```


```{r}
write.csv(movementRel, paste0("../../Data/Brain_Data/MovementRel_",Sys.Date(),".csv"),row.names = FALSE)
```


```{r}
setwd("../../Data/Movement_Absolute")

alldata = list.files(recursive = TRUE, pattern = "Movement_AbsoluteRMS.txt")
head(alldata)
subnames = substr(alldata,1,7)
alldata = lapply(alldata, read.csv, header=FALSE) 

for (sub in 1:length(alldata)) {
  alldata[[sub]]$volnums = 1:720
  alldata[[sub]]$subid = subnames[sub]
}

movementAbs = Reduce(function(...)merge(...,all=T),alldata)
```


```{r}
write.csv(movementAbs, paste0("../../Data/Brain_Data/MovementAbs_",Sys.Date(),".csv"),row.names = FALSE)
```


```{r}
# use either movement file here...

movement = read.csv("../../Data/Brain_Data/MovementAbs_2024-08-13.csv",stringsAsFactors = FALSE, header=TRUE)
#movement = read.csv("../../Data/Brain_Data/MovementRel_2024-08-13.csv",stringsAsFactors = FALSE, header=TRUE)

dim(movement)
dim(blong)

blong2 = merge(blong, movement, all.x = TRUE)
dim(blong2)
```


Check how movement relates to state classification
```{r}

# for each state and participant, get average movement

# intialize aggregate dataframe
bwide = aggregate(list(movement1=blong2$V1[blong2$all_states_path2==1]),
                                list(participant=blong2$subid[blong2$all_states_path2==1]),
                                mean)
# add other states
bwide$movement2 <- aggregate(list(movement2=blong2$V1[blong2$all_states_path2==2]),
                                list(participant=blong2$subid[blong2$all_states_path2==2]),
                                mean)$movement2
bwide$movement3 <- aggregate(list(movement3=blong2$V1[blong2$all_states_path2==3]),
                                list(participant=blong2$subid[blong2$all_states_path2==3]),
                                mean)$movement3
bwide$movement4 <- aggregate(list(movement4=blong2$V1[blong2$all_states_path2==4]),
                                list(participant=blong2$subid[blong2$all_states_path2==4]),
                                mean)$movement4
bwide$movement5 <- aggregate(list(movement5=blong2$V1[blong2$all_states_path2==5]),
                                list(participant=blong2$subid[blong2$all_states_path2==5]),
                                mean)$movement5
bwide$movement6 <- aggregate(list(movement6=blong2$V1[blong2$all_states_path2==6]),
                                list(participant=blong2$subid[blong2$all_states_path2==6]),
                                mean)$movement6
bwide$movement7 <- aggregate(list(movement7=blong2$V1[blong2$all_states_path2==7]),
                                list(participant=blong2$subid[blong2$all_states_path2==7]),
                                mean)$movement7


# get average movement when state is absent:

bwide$movement_not1 <- aggregate(list(movement_not1=blong2$V1[blong2$all_states_path2!=1]),
                                list(participant=blong2$subid[blong2$all_states_path2!=1]),
                                mean)$movement_not1
bwide$movement_not2 <- aggregate(list(movement_not2=blong2$V1[blong2$all_states_path2!=2]),
                                list(participant=blong2$subid[blong2$all_states_path2!=2]),
                                mean)$movement_not2
bwide$movement_not3 <- aggregate(list(movement_not3=blong2$V1[blong2$all_states_path2!=3]),
                                list(participant=blong2$subid[blong2$all_states_path2!=3]),
                                mean)$movement_not3
bwide$movement_not4 <- aggregate(list(movement_not4=blong2$V1[blong2$all_states_path2!=4]),
                                list(participant=blong2$subid[blong2$all_states_path2!=4]),
                                mean)$movement_not4
bwide$movement_not5 <- aggregate(list(movement_not5=blong2$V1[blong2$all_states_path2!=5]),
                                list(participant=blong2$subid[blong2$all_states_path2!=5]),
                                mean)$movement_not5
bwide$movement_not6 <- aggregate(list(movement_not6=blong2$V1[blong2$all_states_path2!=6]),
                                list(participant=blong2$subid[blong2$all_states_path2!=6]),
                                mean)$movement_not6
bwide$movement_not7 <- aggregate(list(movement_not7=blong2$V1[blong2$all_states_path2!=7]),
                                list(participant=blong2$subid[blong2$all_states_path2!=7]),
                                mean)$movement_not7


# do separately for state 8 since not everyone has it:

bwide8 <- aggregate(list(movement8=blong2$V1[blong2$all_states_path2==8]),
                                list(participant=blong2$subid[blong2$all_states_path2==8]),
                                mean, na.rm=T)

bwidenot8 <- aggregate(list(movement_not8=blong2$V1[blong2$all_states_path2!=8]),
                                list(participant=blong2$subid[blong2$all_states_path2!=8]),
                                mean)

bwide8a = merge(bwide8, bwidenot8, all.x=TRUE)

```

```{r}
 # absolute movement results
t.test(bwide$movement1, bwide$movement_not1, paired = TRUE) # ns, p = .4596
t.test(bwide$movement2, bwide$movement_not2, paired = TRUE) # sig., but neg., p=.008085
t.test(bwide$movement3, bwide$movement_not3, paired = TRUE) # ns, p=.1761
t.test(bwide$movement4, bwide$movement_not4, paired = TRUE) # sig., but neg, p=.008126
t.test(bwide$movement5, bwide$movement_not5, paired = TRUE) # sig., p=2.255e-05*... diff=.0543
t.test(bwide$movement6, bwide$movement_not6, paired = TRUE) # sig., but neg., p=.0001488
t.test(bwide$movement7, bwide$movement_not7, paired = TRUE) # ns, p=.1921
t.test(bwide8a$movement8, bwide8a$movement_not8, paired = TRUE) # sig., p=.03658*

# get list of p-values for correction
plist1a = c(.4596, .008085, .1761, .008126, 2.255e-05, .0001488, .1921, .03658)
names(plist1a) = paste0("movement2_", 1:8)
```

```{r}

# with notes from relative movement tests...
t.test(bwide$movement1, bwide$movement_not1, paired = TRUE) # ns, p = .05222
t.test(bwide$movement2, bwide$movement_not2, paired = TRUE) # sig., p=7.845e-05
t.test(bwide$movement3, bwide$movement_not3, paired = TRUE) # sig., p=1.974e-12
t.test(bwide$movement4, bwide$movement_not4, paired = TRUE) # ns, p=.2428
t.test(bwide$movement5, bwide$movement_not5, paired = TRUE) # ns, p=.8857
t.test(bwide$movement6, bwide$movement_not6, paired = TRUE) # sig., but neg., p=3.294e-08
t.test(bwide$movement7, bwide$movement_not7, paired = TRUE) # sig., but neg., p=.000502
t.test(bwide8a$movement8, bwide8a$movement_not8, paired = TRUE) # ns, p=.1037

# relative movement results:
plist1b = c(.05222, 7.845e-05, 1.974e-12, .2428, .8857, 3.294e-08, .000502, .1037)
names(plist1b) = paste0("movement", 1:8)

# FDR correction further down.
```

Now check SNR for each state.
```{r}
setwd("../Data/Raw_Brain_Data/")

alldata = list.files(recursive = TRUE, pattern = "*.txt")
head(alldata)
subnames = substr(alldata,15,21)
alldata = lapply(alldata, read.table, header=FALSE) 

for (sub in 1:length(alldata)) {
  nvols = nrow(alldata[[sub]])
  nstart = 1 + (720 - nvols)
  alldata[[sub]]$volnums = nstart:720
  alldata[[sub]]$subid = subnames[sub]
}

mydata3 = Reduce(function(...)rbind(...),alldata)

write.csv(mydata3, paste0("../Data/Brain_Data/Raw_Merged_ROIs_",Sys.Date(),".csv"),row.names = FALSE)
```


```{r}
# large file, takes a minute...
mydata3 = read.csv("../../Data/Brain_Data/Raw_Merged_ROIs_2024-05-20.csv", header = TRUE, stringsAsFactors = FALSE)
```

```{r}
dim(mydata3)
names(mydata3)

blong3 = merge(blong, mydata3, all.x = TRUE)
dim(blong3)
```

```{r}

#compute temporal SNR for each state, for each person
# final data should have ~157 observations of SNR for each state
# First, compute mean activation for each ROI, for each state, within each person
# Then, compute sd for each ROI for each state, within each person
# Then compute SNR for each ROI, for each person
# Then compute average SNR

# start by selecting only columns we need
blong4 = subset(blong3, select = c("all_states_path2", "subid", grep("V", names(blong3),value=TRUE)))

snr = function(x) {
  mean(x, na.rm=T) / sd(x, na.rm=T)
}

# warnings are ok
rois = aggregate(blong4, list("state"=blong4$all_states_path2, "subid"=blong4$subid), snr)

rois$snr_avg = rowMeans(rois[,grep("V",names(rois))])

state_avg = aggregate(list("snr"=rois$snr_avg), list("state"=rois$state), mean, na.rm=T)
state_avg

```

```{r}

# t-tests when state is present vs not:

# initiate summary df
swide = aggregate(list(snr_1=rois$snr_avg[rois$state==1]),
                                list(participant=rois$subid[rois$state==1]),
                                mean)
# add other states
swide$snr_2 = aggregate(list(snr_2=rois$snr_avg[rois$state==2]),
                                list(participant=rois$subid[rois$state==2]),
                                mean)$snr_2
swide$snr_3 = aggregate(list(snr_3=rois$snr_avg[rois$state==3]),
                                list(participant=rois$subid[rois$state==3]),
                                mean)$snr_3
swide$snr_4 = aggregate(list(snr_4=rois$snr_avg[rois$state==4]),
                                list(participant=rois$subid[rois$state==4]),
                                mean)$snr_4
swide$snr_5 = aggregate(list(snr_5=rois$snr_avg[rois$state==5]),
                                list(participant=rois$subid[rois$state==5]),
                                mean)$snr_5
swide$snr_6 = aggregate(list(snr_6=rois$snr_avg[rois$state==6]),
                                list(participant=rois$subid[rois$state==6]),
                                mean)$snr_6
swide$snr_7 = aggregate(list(snr_7=rois$snr_avg[rois$state==7]),
                                list(participant=rois$subid[rois$state==7]),
                                mean)$snr_7


swide$snr_not1 = aggregate(list(snr_not1=rois$snr_avg[rois$state!=1]),
                                list(participant=rois$subid[rois$state!=1]),
                                mean)$snr_not1
swide$snr_not2 = aggregate(list(snr_not2=rois$snr_avg[rois$state!=2]),
                                list(participant=rois$subid[rois$state!=2]),
                                mean)$snr_not2
swide$snr_not3 = aggregate(list(snr_not3=rois$snr_avg[rois$state!=3]),
                                list(participant=rois$subid[rois$state!=3]),
                                mean)$snr_not3
swide$snr_not4 = aggregate(list(snr_not4=rois$snr_avg[rois$state!=4]),
                                list(participant=rois$subid[rois$state!=4]),
                                mean)$snr_not4
swide$snr_not5 = aggregate(list(snr_not5=rois$snr_avg[rois$state!=5]),
                                list(participant=rois$subid[rois$state!=5]),
                                mean)$snr_not5
swide$snr_not6 = aggregate(list(snr_not6=rois$snr_avg[rois$state!=6]),
                                list(participant=rois$subid[rois$state!=6]),
                                mean)$snr_not6
swide$snr_not7 = aggregate(list(snr_not7=rois$snr_avg[rois$state!=7]),
                                list(participant=rois$subid[rois$state!=7]),
                                mean)$snr_not7

# do separately for state 8 since not everyone has it...

swide8 <- aggregate(list(snr_8=rois$snr_avg[rois$state==8]),
                                list(participant=rois$subid[rois$state==8]),
                                mean)

swidenot8 <- aggregate(list(snr_not8=rois$snr_avg[rois$state!=8]),
                                list(participant=rois$subid[rois$state!=8]),
                                mean)

swide8a = merge(swide8, swidenot8, all.x=TRUE)

```

```{r}
# neg is bad
t.test(swide$snr_1, swide$snr_not1, paired = TRUE) # ns, p=.06994
t.test(swide$snr_2, swide$snr_not2, paired = TRUE) # sig., neg., p=.03102
t.test(swide$snr_3, swide$snr_not3, paired = TRUE) # sig., neg., p=.01423
t.test(swide$snr_4, swide$snr_not4, paired = TRUE) # ns, p=.2371
t.test(swide$snr_5, swide$snr_not5, paired = TRUE) # sig., neg., p=.0441
t.test(swide$snr_6, swide$snr_not6, paired = TRUE) # ns, p=.7452
t.test(swide$snr_7, swide$snr_not7, paired = TRUE) # ns, p=.4444
t.test(swide8a$snr_8, swide8a$snr_not8, paired = TRUE) # ns, p=.1253
```

FDR correction: looking at movement & SNR together
```{r}

plist2 = c(.06994, .03102, .01423, .2371, .0441, .7452, .4444, .1253)
names(plist2) = paste0("snr_", 1:8)

# add back in movement p-values
plist3a = c(plist1a, plist2)
plist3a

sort(round(p.adjust(plist3a,"BH"),3))
# state 5 movement is only one that survives and is not negative...
# SNR state 3 is also flagged

# visualize and check for outliers
bwide$movediff5 = bwide$movement5 - bwide$movement_not5
hist(bwide$movediff5)

mod1 = lm(bwide$movediff5 ~ 1)
summary(mod1) # sig.
plot(mod1) # 81 & 95 look like outliers

which(bwide$movediff5 > .5) # 81 & 95
bwide$dummy_81 = 1*(row.names(bwide)==81)
bwide$dummy_95 = 1*(row.names(bwide)==95)
bwide$dummy_92 = 1*(row.names(bwide)==92)

mod2 = lm(movediff5 ~ 1 + dummy_81 + dummy_95 + dummy_92, data=bwide) # still sig. with dummies
summary(mod2)

```

Relative movement
```{r}
# relative movement
plist3b = c(plist1b, plist2)
sort(round(p.adjust(plist3b,"BH"),3))


# just SNR- nothing survives
sort(round(p.adjust(plist2,"fdr"),3))

```

