---
title: "CAP validation analyses"
author: "Elena Peterson"
date: "2024-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages & data files
```{r}
library(lme4)
library(lmerTest)
```

```{r}
dwide = read.csv("../../Data/Brain_Data/CAP_measures_overall_2024-04-10.csv",stringsAsFactors = FALSE, header=TRUE)
dlong = read.csv("../../Data/Brain_Data/CAP_k8_long_sequence_2024-07-05.csv",stringsAsFactors = FALSE, header=TRUE)

#dtest = read.csv("../../Data/Merged_Data/Merged_Data_9s_n154_2024-06-18.csv",stringsAsFactors = FALSE, header=TRUE)

#sublist = unique(dtest$participant)
```

```{r}
# exclude additional subjects
exc1 = c("sub-001", "sub-146", "sub-092", "sub-016", "sub-032")

dwide = dwide[!(dwide$subid %in% exc1),]

sum(dwide$overall_ts_8==0) # 46

dlong = dlong[!(dlong$subid %in% exc1),]
length(unique(dlong$subid)) # 154
```
Identify states that are responsive to changes in WM load
```{r}
t.test(dwide$ts_1_0back, dwide$ts_1_2back, paired=TRUE) # sig., 0-back responsive
t.test(dwide$ts_2_0back, dwide$ts_2_2back, paired=TRUE) # sig., 0-back responsive
t.test(dwide$ts_3_0back, dwide$ts_3_2back, paired=TRUE) # marginal, 0-back responsive
t.test(dwide$ts_4_0back, dwide$ts_4_2back, paired=TRUE) # ns
t.test(dwide$ts_5_0back, dwide$ts_5_2back, paired=TRUE) # ns
t.test(dwide$ts_6_0back, dwide$ts_6_2back, paired=TRUE) # sig. # this one, 2-back responsive
t.test(dwide$ts_7_0back, dwide$ts_7_2back, paired=TRUE) # sig. 0-back responsive
t.test(dwide$ts_8_0back, dwide$ts_8_2back, paired=TRUE) # sig., 2-back responsive

```

```{r}
# subset df by block/trial type:

# preceding errors- trials are 2.5 seconds long... so maybe just 3 vols = 2.4 seconds
derrors = dlong[dlong$errors_dist_inv<=3,]

# preceding long RTs
dlongRTs = dlong[dlong$long_rts_dist_inv<=3,]

# all task volumes
dAllTask = dlong[dlong$voleventcat=="Block",]

# all 0-back volumes
dAll0b = dlong[dlong$wmload=="0back",]

# all 2-back volumes
dAll2b = dlong[dlong$wmload=="2back",]

# all Fix volumes
dAllFix = dlong[dlong$voleventcat=="Fix",]

# all cue volumes
dAllCue = dlong[dlong$voleventcat=="Cue",]

```

```{r}
# get counts for overall task, not including cue
#################################################
print("Task overall:")
(obs_alltask = table(dAllTask$all_states_path2))  # 7178  7216  5357 17416  9232 15682 13079  1376 
sum(obs_alltask) # 76536

# get counts for overall 0-backs
################################
print("0-backs:")
(obs_all0b = table(dAll0b$all_states_path2))  # 4566 3989 2807 8741 4520 5483 7642  598
sum(obs_all0b) # 38346

# get counts for overall 2-backs
################################
print("2-backs:")
(obs_all2b = table(dAll2b$all_states_path2)) # 2612  3227  2550  8675  4712 10199  5437   778
sum(obs_all2b) # 38190
obs_all2b

# get counts for overall fix
############################
print("Fixation:")
(obs_allFix = table(dAllFix$all_states_path2))
sum(obs_allFix ) 

# get counts for overall cue
#############################
print("Cue periods:")
(obs_allCue = table(dAllCue$all_states_path2))
sum(obs_allCue) 

# get counts for before errors
##############################
print("Error trials:")
(obs_err = table(derrors$all_states_path2)) 
sum(obs_err)

# get counts for before long RTs
##############################
print("Long RT trials:")
(obs_rts = table(dlongRTs$all_states_path2)) 
sum(obs_rts) 

```

```{r}

# see which states are driving differences:
# define function for comparing each pair in table
# must be table with 2 rows
comp_freq = function(tbl) {
  nstates = dim(tbl)[2]
  total1 = sum(tbl[1,])
  total2 = sum(tbl[2,])
  for (b in 1:nstates) {
    r1 = prop.test(x = c(tbl[1,b], tbl[2,b]), n = c(total1, total2)) # ns
    print(paste("State", b, ":"))
    print(r1)
  }
}

```

```{r}

# Compare task vs fixation distributions:
##########################################
obs_task_vs_fix <- rbind(obs_alltask, obs_allFix)
chisq.test(obs_task_vs_fix) # sig.

# follow up
comp_freq(obs_task_vs_fix)

# see proportions
obs_alltask/sum(obs_alltask)
obs_allFix/sum(obs_allFix)

# compare 0b vs 2b:
###################
obs_0b_vs_2b <- rbind(obs_all0b, obs_all2b)
chisq.test(obs_0b_vs_2b)

# follow up
comp_freq(obs_0b_vs_2b) # ns for state 4

# see proportions
obs_all0b/sum(obs_all0b)
obs_all2b/sum(obs_all2b)

# compare cue with task:
########################
obs_task_vs_cue <- rbind(obs_alltask, obs_allCue)
chisq.test(obs_task_vs_cue)

# follow up
comp_freq(obs_task_vs_cue)

# see proportions
obs_alltask/sum(obs_alltask)
obs_allCue/sum(obs_allCue)

# Compare long RT trials with tasks overall:
############################################
obs_rts_vs_task <- rbind(obs_rts, obs_alltask)
chisq.test(obs_rts_vs_task) # sig.

# follow up
comp_freq(obs_rts_vs_task) # driven by: 2, 5

# see proportions
obs_rts/sum(obs_rts)
obs_alltask/sum(obs_alltask)

# Compare error trials with tasks overall:
##########################################
obs_err_vs_task <- rbind(obs_err, obs_alltask)
chisq.test(obs_err_vs_task) # sig.

# follow up
comp_freq(obs_err_vs_task) # 1, 3, 8

# see proportions
obs_err/sum(obs_err)
obs_alltask/sum(obs_alltask)

```

